name: Deploy

on:
  push:
    branches: [main]

jobs:
  migrate-db:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Run migrations
        run: supabase db push --db-url ${{ secrets.PROD_SUPABASE_DB_URL }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

  deploy-vercel:
    runs-on: ubuntu-latest
    needs: migrate-db
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: |
          echo "Deployment triggered by Vercel Git Integration"
          echo "Visit https://vercel.com to see deployment status"
